### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by orbeckst** [jbarnoud/panedr#23]
A conda-forge package would be great because then one could make an EDR-[auxiliary reader for MDAnalysis](https://www.mdanalysis.org/docs/documentation_pages/auxiliary/init.html).

It would also help with an EDR reader for alchemlyb https://github.com/alchemistry/alchemlyb/issues/67.

**Comment by jbarnoud** [comment]
Glad to see you here @orbeckst. There is already a conda-forge package: https://anaconda.org/conda-forge/panedr

I will add it to the documentation.

**Comment by orbeckst** [comment]
Cool, thank you!
