### ISSUE TITLE
I'm getting the following error: "UserWarning: Note: enx file_version 1, implementation version 5"

### ISSUE THREAD

**Issue by djamp88** [jbarnoud/panedr#24]

**Comment by djamp88** [comment]
C:\Users\DJHOME\anaconda3\lib\site-packages\panedr\panedr.py:118: UserWarning: Note: enx file_version 1, implementation version 5
  warnings.warn('Note: enx file_version {}, implementation version {}'.format(file_version, ENX_VERSION))
---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
<ipython-input-14-c8c42292f024> in <module>
      1 path = '34-CA037.088'
----> 2 df = panedr.edr_to_df(path)

~\anaconda3\lib\site-packages\panedr\panedr.py in edr_to_df(path, verbose)
    405 def edr_to_df(path, verbose=False):
    406     begin = time.time()
--> 407     edr_file = EDRFile(str(path))
    408     all_energies = []
    409     all_names = [u'Time'] + [nm.name for nm in edr_file.nms]

~\anaconda3\lib\site-packages\panedr\panedr.py in __init__(self, path)
     84             content = infile.read()
     85         self.data = GMX_Unpacker(content)
---> 86         self.do_enxnms()
     87 
     88     def __iter__(self):

~\anaconda3\lib\site-packages\panedr\panedr.py in do_enxnms(self)
    117         if file_version != ENX_VERSION:
    118             warnings.warn('Note: enx file_version {}, implementation version {}'.format(file_version, ENX_VERSION))
--> 119         nms = edr_strings(data, file_version, nre)
    120 
    121         self.file_version = file_version

~\anaconda3\lib\site-packages\panedr\panedr.py in edr_strings(data, file_version, n)
    385     nms = []
    386     for i in range(n):
--> 387         name = data.unpack_string().decode('ascii')
    388         if file_version >= 2:
    389             unit = data.unpack_string().decode('ascii')

~\anaconda3\lib\xdrlib.py in unpack_string(self)
    215     def unpack_string(self):
    216         n = self.unpack_uint()
--> 217         return self.unpack_fstring(n)
    218 
    219     unpack_opaque = unpack_string

~\anaconda3\lib\xdrlib.py in unpack_fstring(self, n)
    207         j = i + (n+3)//4*4
    208         if j > len(self.__buf):
--> 209             raise EOFError
    210         self.__pos = j
    211         return self.__buf[i:i+n]

EOFError:

**Comment by jbarnoud** [comment]
Hi,

Thank you for reporting the issue. What version of gromacs did you use to generate the edr file?

**Comment by djamp88** [comment]
Not 100% sure.

The. edr file was generated by aircraft engine trend monitoring equipment that was developed around 1990 and probably wasn’t updated much since then.

**Comment by jbarnoud** [comment]
It looks like we are not talking about the same EDR files, then. `panedr` reads energy files produced by the molecular simulation engine called gromacs: http://www.gromacs.org/.

**Comment by djamp88** [comment]
Yeah. I can see that.

The file pulls up just fine on Filext.com as an .edr file (.edr files in Filext.com are also labeled for files generated with Gromacs and Embird).  Therefore, I was hoping panedr would be able to process it as well.


Is it “not working” a matter of a specific format within the .edr file?

**Comment by jbarnoud** [comment]
The EDR files produced by gromacs are fairly ad hoc. I am afraid the shared name/extension is just a coincidence.

**Comment by djamp88** [comment]
Understood.

Thank you for your feedback.
