### ISSUE TITLE
add CHANGELOG file

### ISSUE THREAD

**Issue by orbeckst** [jbarnoud/panedr#44]
With panedr evolving towards a building block for other libraries (namely, MDAnalysis) it becomes more important to document changes. 

I'd also strongly suggest to formally adopt [semantic versioning](https://semver.org).

**Comment by hmacdope** [comment]
@orbeckst do we want to add `versioneer` as part of adopting semver?

**Comment by orbeckst** [comment]
I like it, we use it in our cookiecutter, but I also don't want @BFedder to get bogged down with panedr. I'd say that's a nice-to-have right now and can be left for another day.

**Comment by hmacdope** [comment]
:+1:

**Comment by IAlibay** [comment]
Is pbr not sufficiently following semver? Any reason for choosing to remove it over versioneer?

**Comment by hmacdope** [comment]
I wasn't aware  that `pbr` did all that already my bad.

**Comment by IAlibay** [comment]
Just quickly glancing at things with my phone - seems to me like the issue here is just to make sure release tags are following semver, not that we need to switch version setting tools?

**Comment by orbeckst** [comment]
The _issue_ is about having a CHANGELOG file ;-).

My comment was, as you said, just making sure that release tags are consistent with semver, and stating somewhere that this project adheres to semver.

**Comment by orbeckst** [comment]
And I am not familiar with `pbr` and had already forgotten that I had seen it somewhere. My bad.

**Comment by IAlibay** [comment]
Closed via #51
