### ISSUE TITLE
Reduce size of install

### ISSUE THREAD

**Issue by theavey** [jbarnoud/panedr#9]
I use this package in a package I am working on, and run my tests on Travis-CI. Because the test data comes bundles with the package, each test takes a bit longer because of the size of the download.

I was wondering if it would be possible or practical to make installing the test data optional.

This is not critical at all, but I just thought it would be convenient in some cases.

This package is great and really helps me out, thanks!

**Comment by jbarnoud** [comment]
This is doable indeed. I'll have a look as soon as possible.

**Comment by jbarnoud** [comment]
It should be fixed in version 3.0.1.

**Comment by theavey** [comment]
Great, thank you very much!
